### ISSUE TITLE
Add service to clear the storage ad-hoc

### ISSUE THREAD

**Issue by Exocomp** [koriUA/rxjs-store-persist#1]
Hi there, nice library, would it be possible to add a service I can inject then call a function to delete the indexedDb.  For example, upon logout, I would like to call such a method to delete any data.

**Comment by koriUA** [comment]
Hi. Thanks. I guess you don't need such service. You can just dispatch action to clear the store on logout and rxjs-store-persist automatically synchronizes indexedDb and cleares the store. In your case, if you clear indexedDb but don't clear store there will be desynchronization beetwen store and indexedDb.
